name: PR Merged

on:
  workflow_call:

jobs:
  mark_merged_prs_as_completed:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true}}
    environment: staging
    steps:
      - name: Label PR Completed
        uses: andymckay/labeler@master
        with:
          add-labels: 'status:completed'
          remove-labels: 'status:qa, status:review'
