name: PR Ready For Review

on:
  workflow_call:

jobs:
  in_development:
    runs-on: ubuntu-latest
    environment: development
    if: github.event.pull_request.draft == true
    steps:
      - name: Label PR Development
        uses: andymckay/labeler@master
        with:
          add-labels: 'status:development'
  request_review:
    runs-on: ubuntu-latest
    environment: development
    if: github.event.pull_request.draft == false
    steps:
      - name: Label PR In Review
        uses: andymckay/labeler@master
        with:
          add-labels: 'status:review'
          remove-labels: 'status:development'